### ISSUE TITLE
BOE not showen in some cases in bagnon

### ISSUE THREAD

**Issue by scaxfull** [GoldpawsStuff/Bagnon_ItemInfo#1]
Hello,

The BOE its only shown in main bag bank+ character, when you move it to others bags the mention of boe disappears . i have made a test with a zandalar item (all addons off) bagnon iteminfo nothing change.

You can check screenshot here maybe its a language issue https://ibb.co/T8J7hCr

Thanks

**Comment by macrobin268** [comment]
Hello,

If I set WoW in English, there is no problem. But if I configure WoW in French, BoE does not appear.

Tested with the latest version 1.0.18-Release.

Would it also be possible to make this addon compatible with Combuctor (classic Bagnon) ?

Thanks

**Comment by Minoz794** [comment]
Please update 🙂

**Comment by Goldpaw** [comment]
Since this addon uses the same code as my other bagnon plugins combined, I'm closing this issue and keeping the bug tracking of the frFR problem over at bagnon BoE instead: 
https://github.com/GoldpawsStuff/Bagnon_BoE/issues/7
