### ISSUE TITLE
Error on start with new release of Bagnon ver. 9

### ISSUE THREAD

**Issue by BenBelatrix** [GoldpawsStuff/Bagnon_ItemInfo#10]
`Message: Interface\AddOns\Bagnon_ItemInfo\main.lua:513: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Wed Sep 23 13:17:18 2020
Count: 1
Stack: Interface\AddOns\Bagnon_ItemInfo\main.lua:513: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Bagnon_ItemInfo\main.lua"]:513: in main chunk

Locals: (*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 StoreMicroButtonAlertGlowBottom = StoreMicroButtonAlertGlowBottom {
 }
 AllTheThings-SettingsScrollUpButton = AllTheThings-SettingsScrollUpButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2379
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 950
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:957
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButt`

**Comment by gaveer** [comment]
Same Error show up @goldpaw

**Comment by BenBelatrix** [comment]
> go to line 513 in **main.lua**
> `hooksecurefunc(Bagnon.ItemSlot, "Update", Update)`
> replace it with
> `hooksecurefunc(Bagnon.Item, "Update", Update)`

It works - THANK YOU

**Comment by goldpaw** [comment]
Fixed in latest update.
