### ISSUE TITLE
BoE label not removed when equipping a BoE item.

### ISSUE THREAD

**Issue by LudiusMaximus** [GoldpawsStuff/Bagnon_ItemInfo#13]
https://i.imgur.com/Q8dQ0Ce.mp4
(Version was: 1.0.23)

Thanks! :-)

**Comment by goldpaw** [comment]
Should be fixed  in 1.0.24-Release!

**Comment by LudiusMaximus** [comment]
> Should be fixed in 1.0.24-Release!

Great, works like a charm! Thanks for the immediate action! :-D
