### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by chibraltar** [GoldpawsStuff/Bagnon_ItemInfo#41]
not showing ilvl, tried loaded only depency addons same error 

10x Bagnon_ItemInfo/Modules/Itemlevel.lua:29: Cannot find a library instance of "LibItemCache-2.0".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Bagnon_ItemInfo/Modules/Itemlevel.lua"]:29: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibItemCache-2.0"."

**Comment by finrodbr** [comment]
Bagnon_ItemInfo uses this library to cache its results. There is a simple workaround to this error: download the library here: https://github.com/Jaliborc/LibItemCache-2.0/tree/master

Then go to the \World of Warcraft\_classic_\Interface\AddOns\Bagnon_ItemInfo\Libs folder and unzip it there

Then modify the Embeds.xml file to add the following line after the LibStub Script tag:
<Script file="Libs\LibItemCache-2.0\LibItemCache-2.0.lua"/>

That should do it

**Comment by chibraltar** [comment]
@finrodbr thx mate
