### ISSUE TITLE
outdated at 8.3.0

### ISSUE THREAD

**Issue by vmwinckler** [GoldpawsStuff/Bagnon_ItemInfo#8]
outdated at 8.3.0

**Comment by goldpaw** [comment]
Yeah but does it work? with the "load out of date addons" checkbox? Not a bug if it does. It is tagged for 8.2.5, and works for 8.2.5, and if it works for 8.3.0 with the box checked, it's not bugged.

**Comment by goldpaw** [comment]
Closing as it works with 9.x and is fully updated.
